// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_luzrpDx9gtahhs47EwMdn8d5GhqotX0',
    appId: '1:73659945988:web:09c07743d18d0f29749151',
    messagingSenderId: '73659945988',
    projectId: 'master-case-c2dcc',
    authDomain: 'master-case-c2dcc.firebaseapp.com',
    storageBucket: 'master-case-c2dcc.firebasestorage.app',
    measurementId: 'G-7922XBQHR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ueamFG5ydmri0aSbEaJX4VU3uUEtVDE',
    appId: '1:73659945988:android:39d19f4b55f3cf42749151',
    messagingSenderId: '73659945988',
    projectId: 'master-case-c2dcc',
    storageBucket: 'master-case-c2dcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWTnONdf8u_Hffw83qv8MVXz7bO5jq_x0',
    appId: '1:73659945988:ios:0ad2d08b46edac18749151',
    messagingSenderId: '73659945988',
    projectId: 'master-case-c2dcc',
    storageBucket: 'master-case-c2dcc.firebasestorage.app',
    iosBundleId: 'com.obvioservices.mastercase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWTnONdf8u_Hffw83qv8MVXz7bO5jq_x0',
    appId: '1:73659945988:ios:de031b54cdd555f8749151',
    messagingSenderId: '73659945988',
    projectId: 'master-case-c2dcc',
    storageBucket: 'master-case-c2dcc.firebasestorage.app',
    iosBundleId: 'com.example.masterCase',
  );
}